CREATE DATABASE rkv;
GO
USE rkv;
GO

CREATE TABLE dbo.DEPT (
  DEPTNO INT PRIMARY KEY,
  DNAME VARCHAR(50),
  LOC VARCHAR(50)
);

INSERT INTO dbo.DEPT (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON'),
(50, 'Test Dept', 'Toronto');

